
services:
  weather_api:
    container_name: weather-api-container
    build:
      context: ..
      dockerfile: src/Weather.Api/Dockerfile
    ports:
      - "5000:8080"    
    restart: unless-stopped    
